/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taller_vehicular;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author K
 */
public class R_VEHICULOS extends javax.swing.JFrame { 
    phpmyadmin con = new phpmyadmin();
    private final int COSTO_AUTOMOVIL = 20000;
    private final int COSTO_CAMIONETA = 30000;

    /**
     * Creates new form R_VEHICULOS
     */
    public R_VEHICULOS() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarFechaActual();
        
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
    }
    
    private void mostrarFechaActual() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String fechaActual = dateFormat.format(date);
        fecha_i.setText(fechaActual);
        fecha_e.setText(fechaActual);
    }
    
    private int calcularCostoManoDeObra(int horasTrabajadas, String tipoVehiculo) {
        int costoPorHora = 0;

        if ("Automóvil".equals(tipoVehiculo)) {
            costoPorHora = COSTO_AUTOMOVIL;
        } else if ("Camioneta".equals(tipoVehiculo)) {
            costoPorHora = COSTO_CAMIONETA;
        }

        return horasTrabajadas * costoPorHora;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Siguiente = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        tipo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        tarjeta_p = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        Siguiente1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fecha_i = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fecha_e = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fecha2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        Enviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        repuestos = new javax.swing.JTable();
        mano = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        B_total = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("TALLER VEHICULAR");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 70));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("TIPO DE VEHICULO");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        placa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel4.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("PLACA");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setText("ESTADO");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opcion", "Bueno", "Regular", "Malo" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 190, 40));

        Siguiente.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Siguiente.setText("SIGUIENTE");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        jPanel4.add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel15.setText("MOTIVO DE INGRESO");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 570, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opcion", "Mecánica en general", "Cambio de aceite", "Alineación y rotación de ruedas", "Sistemas de suspensión ", "Chapa y pintura", "Reparación de llantas", "Aire acondicionado y calefacción", "Servicio de Frenos", "Otro" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 680, 40));

        tipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel4.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 180, 40));

        jTabbedPane1.addTab("Datos del vehiculo", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("CEDULA");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("NOMBRES");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("APELLIDOS");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 140, -1));

        nombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 220, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setText("TARJETA DE PROPIETARIO");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        direccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 320, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setText("DIRECCIÓN");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        apellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 220, 40));

        tarjeta_p.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(tarjeta_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setText("CORREO");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        correo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 320, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel11.setText("TELEFONO");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 160, 40));

        Siguiente1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Siguiente1.setText("SIGUIENTE");
        Siguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Siguiente1ActionPerformed(evt);
            }
        });
        jPanel6.add(Siguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jTabbedPane1.addTab("Datos cliente", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setText("COSTO DE SERVICIO");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        fecha_i.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_iActionPerformed(evt);
            }
        });
        jPanel7.add(fecha_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel13.setText("FECHA ENTREGA");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        fecha_e.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_eActionPerformed(evt);
            }
        });
        jPanel7.add(fecha_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel14.setText("HORAS DE TRABAJO");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, -1));

        fecha2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha2ActionPerformed(evt);
            }
        });
        jPanel7.add(fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel17.setText("FECHA INGRESO");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel19.setText("REPUESTOS");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel7.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 140, 40));

        Enviar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Enviar.setText("ENVIAR");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        jPanel7.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 140, 40));

        repuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "REPUESTO", "PRECIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(repuestos);
        if (repuestos.getColumnModel().getColumnCount() > 0) {
            repuestos.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 300, 190));
        jPanel7.add(mano, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 250, 40));

        calcular.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        calcular.setText("MANO DE OBRA");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        jPanel7.add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 190, 40));

        B_total.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        B_total.setText("TOTAL");
        B_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_totalActionPerformed(evt);
            }
        });
        jPanel7.add(B_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 140, 40));

        jTabbedPane1.addTab("Datos adicionales", jPanel7);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 360));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        String tipoVehiculo = tipo.getText().trim();

        if (!tipoVehiculo.equalsIgnoreCase("Automóvil") && !tipoVehiculo.equalsIgnoreCase("Camioneta")) {
            JOptionPane.showMessageDialog(this, "Tipo de vehículo incorrecto. El taller no suministra servicios a vehículos de tráfico pesado. Seleccione Automóvil o Camioneta");
            return;
        }
        
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_SiguienteActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void Siguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Siguiente1ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_Siguiente1ActionPerformed

    private void fecha_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_iActionPerformed

    private void fecha_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_eActionPerformed

    private void fecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        String placaVehiculo = placa.getText();
    String tipoVehiculo = (String) tipo.getText();
    String estadoVehiculo = (String) jComboBox2.getSelectedItem();
    String motivoIngreso = (String) jComboBox3.getSelectedItem();
    int cedulaCliente = Integer.parseInt(cedula.getText());
    String nombresCliente = nombres.getText();
    String apellidosCliente = apellidos.getText();
    String tarjetaPropietario = tarjeta_p.getText();
    String direccionCliente = direccion.getText();
    String correoCliente = correo.getText();
    int telefonoCliente = Integer.parseInt(telefono.getText());

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String fechaIngreso = dateFormat.format(new Date(fecha_i.getText()));
    String fechaEntrega = dateFormat.format(new Date(fecha_e.getText()));

    int horasTrabajadas = Integer.parseInt(fecha2.getText());
    int costoManoDeObra = calcularCostoManoDeObra(horasTrabajadas, tipoVehiculo);
    
    int costoTotal = Integer.parseInt(total.getText());

    String consultaSQL = "INSERT INTO vehiculo (Placa, Tipo, Estado, Motivo, Cedula, Nombres, Apellidos, Tarjeta, Direccion, Correo, Telefono, Fecha_ingreso, Fecha_entrega, Mano_obra, Total) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try {
        Connection conexion = con.getConectarDB();
        PreparedStatement pstmt = conexion.prepareStatement(consultaSQL);
        pstmt.setString(1, placaVehiculo);
        pstmt.setString(2, tipoVehiculo);
        pstmt.setString(3, estadoVehiculo);
        pstmt.setString(4, motivoIngreso);
        pstmt.setInt(5, cedulaCliente);
        pstmt.setString(6, nombresCliente);
        pstmt.setString(7, apellidosCliente);
        pstmt.setString(8, tarjetaPropietario);
        pstmt.setString(9, direccionCliente);
        pstmt.setString(10, correoCliente);
        pstmt.setInt(11, telefonoCliente);
        pstmt.setString(12, fechaIngreso);
        pstmt.setString(13, fechaEntrega);
        pstmt.setInt(14, costoManoDeObra);
        pstmt.setInt(15, costoTotal);

        int filasAfectadas = pstmt.executeUpdate();
        System.out.println("Filas afectadas: " + filasAfectadas);

        conexion.close();

        System.out.println("Datos enviados a la base de datos correctamente.");
        JOptionPane.showMessageDialog(this, "Vehiculo Registrado");
        jTabbedPane1.setSelectedIndex(0);
    } catch (Exception ex) {
        ex.printStackTrace();
        System.out.println("Error al enviar datos a la base de datos: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Error al registrar");
        jTabbedPane1.setSelectedIndex(0);
    }

    placa.setText("");
    tipo.setText("");
    jComboBox2.setSelectedIndex(0);
    jComboBox3.setSelectedIndex(0);
    cedula.setText("");
    nombres.setText("");
    apellidos.setText("");
    tarjeta_p.setText("");
    direccion.setText("");
    correo.setText("");
    telefono.setText("");
    fecha_i.setText("");
    fecha_e.setText("");
    fecha2.setText("");
    total.setText("");
    mano.setText("");
    }//GEN-LAST:event_EnviarActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int horasTrabajadas = Integer.parseInt(fecha2.getText());
        String tipoVehiculo = tipo.getText().trim();

        int costoManoDeObra = calcularCostoManoDeObra(horasTrabajadas, tipoVehiculo);

        mano.setText(String.valueOf(costoManoDeObra));
    }//GEN-LAST:event_calcularActionPerformed

    private void B_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_totalActionPerformed
        try {
        int horasTrabajadas = Integer.parseInt(fecha2.getText());
        String tipoVehiculo = tipo.getText().trim();

        int costoPorHora = 0;

        if ("Automóvil".equals(tipoVehiculo)) {
            costoPorHora = COSTO_AUTOMOVIL;
        } else if ("Camioneta".equals(tipoVehiculo)) {
            costoPorHora = COSTO_CAMIONETA;
        }

        int costoManoDeObra = horasTrabajadas * costoPorHora;

        DefaultTableModel model = (DefaultTableModel) repuestos.getModel();

        int costoRepuestos = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 1);

            if (value != null) {
                costoRepuestos += (Integer) value;
            }
        }

        int costoTotal = costoManoDeObra + costoRepuestos;

        total.setText(String.valueOf(costoTotal));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al calcular los costos. Asegúrate de ingresar valores numéricos válidos.");
    }
    }//GEN-LAST:event_B_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(R_VEHICULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(R_VEHICULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(R_VEHICULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(R_VEHICULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new R_VEHICULOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_total;
    private javax.swing.JButton Enviar;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton Siguiente1;
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField fecha2;
    private javax.swing.JTextField fecha_e;
    private javax.swing.JTextField fecha_i;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mano;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField placa;
    private javax.swing.JTable repuestos;
    private javax.swing.JTextField tarjeta_p;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField tipo;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
